name: CI Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      #finally build your app with the latest commandd
      - name: Build and test with Maven
        run: mvn clean install
        working-directory: simple-api
      - name: Build and test with
        run: mvn -B verify sonar:sonar
          -Dsonar.projectKey=Yasminebahroun1_devops-livecoding
          -Dsonar.organization=yasminebahroun1
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml

